### ISSUE TITLE
我想咨询一下，linux命令行的版本One Step Miner，如何批量处理多个fastq文件？

### ISSUE THREAD

**Issue by Ryvesselt** [kli28/sRNAminer#1]
还是说一次只能读取一个fastq文件。请您指教。

**Comment by kli28** [comment]
两种方式：
1. 增加"--Batch_mode"参数，-i参数输入含有多个fastq文件名的文本文件，如：
####file.txt#########
a.fastq
b.fastq
#################
2. -i 后面接多个fastq文件，","分隔

**Comment by Ryvesselt** [comment]
> 两种方式：
> 
>     1. 增加"--Batch_mode"参数，-i参数输入含有多个fastq文件名的文本文件，如：
>        ####file.txt#########
>        a.fastq
>        b.fastq
>        #################
> 
>     2. -i 后面接多个fastq文件，","分隔

感谢您的回复，但我在使用加--Batch Mode参数后，只处理了文本文件中的第一个文件的接头剪切和Collapse程序便停止了。
![图片](https://user-images.githubusercontent.com/62634905/233766417-b0cec82e-4251-4a06-a560-7c2b3d5586c4.png)

文本文件中包含所有fastq文件的的绝对路径地址，每一个占一行。

**Comment by kli28** [comment]
> > 两种方式：
> > ```
> > 1. 增加"--Batch_mode"参数，-i参数输入含有多个fastq文件名的文本文件，如：
> >    ####file.txt#########
> >    a.fastq
> >    b.fastq
> >    #################
> > 
> > 2. -i 后面接多个fastq文件，","分隔
> > ```
> 
> 感谢您的回复，但我在使用加--Batch Mode参数后，只处理了文本文件中的第一个文件的接头剪切和Collapse程序便停止了。 ![图片](https://user-images.githubusercontent.com/62634905/233766417-b0cec82e-4251-4a06-a560-7c2b3d5586c4.png)
> 
> 文本文件中包含所有fastq文件的的绝对路径地址，每一个占一行。

你这里并没有报错信息，看起来并不是停止了，而是因为这里预处理是单个单个样品进行的，因此程序还在运行，你需要等待下一个样品的处理。

**Comment by Ryvesselt** [comment]
> 
![图片](https://user-images.githubusercontent.com/62634905/233921290-b9829f27-d26a-4b5a-934d-4bca332b467e.png)
看来是我图没有截全，它的确是停止了。

**Comment by kli28** [comment]
> > 
> 
> ![图片](https://user-images.githubusercontent.com/62634905/233921290-b9829f27-d26a-4b5a-934d-4bca332b467e.png) 看来是我图没有截全，它的确是停止了。

好的，这比较奇怪，看来需要进一步查看情况，可能要看一下Log的情况，是否可以把您的联系方式发到guanliang_li_28@163.com？如QQ，Wechat等，这样交流更高效些

**Comment by wydsqgg** [comment]
您好，我想请问这个问题解决了吗，因为我同样遇到了这个问题，只能处理第一个fastq，就停止了。

**Comment by kli28** [comment]
> 您好，我想请问这个问题解决了吗，因为我同样遇到了这个问题，只能处理第一个fastq，就停止了。
When you meet this question, try to change your blast version to 2.12
