### ISSUE TITLE
read？

### ISSUE THREAD

**Issue by wangyuhu123** [kli28/sRNAminer#3]
![image](https://github.com/kli28/sRNAminer/assets/70244560/73110cfa-a1d7-4670-bed9-f8251d859173)
When I use one-click analysis, the software prompts me with an error, as shown in the picture. Is there something wrong with my reads?
​

**Comment by kli28** [comment]
> ![image](https://private-user-images.githubusercontent.com/70244560/293644332-73110cfa-a1d7-4670-bed9-f8251d859173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODM4NDAsIm5iZiI6MTcwNDE4MzU0MCwicGF0aCI6Ii83MDI0NDU2MC8yOTM2NDQzMzItNzMxMTBjZmEtYTFkNy00NjcwLWJlZDktZjgyNTFkODU5MTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA4MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOGJlNjFlY2RjNzlhMWIxMjMwYWZlYTJlOGE3MWU0OGEyNTNjY2JkZTY5Y2UzZTk0YzJiNWQyMmVhNzc0YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ljpW3MAtoiFFk6dYkYibO8FuXVkDABCUxsMmZE0sYBQ) When I use one-click analysis, the software prompts me with an error, as shown in the picture. Is there something wrong with my reads?​

Hi. This problem happens when your reads in your sequencing data have the adapters but not in the same length (reads). Because of the difference of the length, sRNAminer will recognize this sequencing file into adapter-trimmed data in the one-step mode, which means sRNAminer will not trim the adapter. So in this way, you can't run the one-step mode, but analyze it step-by-step (Not that difficult, just follow the instruction, no worries).

I recommend you to have a quick check on your sequencing data first to see whether you have the problem mentioned above.

**Comment by wangyuhu123** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/70244560/293644332-73110cfa-a1d7-4670-bed9-f8251d859173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODM4NDAsIm5iZiI6MTcwNDE4MzU0MCwicGF0aCI6Ii83MDI0NDU2MC8yOTM2NDQzMzItNzMxMTBjZmEtYTFkNy00NjcwLWJlZDktZjgyNTFkODU5MTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA4MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOGJlNjFlY2RjNzlhMWIxMjMwYWZlYTJlOGE3MWU0OGEyNTNjY2JkZTY5Y2UzZTk0YzJiNWQyMmVhNzc0YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ljpW3MAtoiFFk6dYkYibO8FuXVkDABCUxsMmZE0sYBQ)当我使用一键分析时，软件提示错误，如图。我的阅读有问题吗？​
> 
> 你好。当测序数据中的读段具有适配器但长度（读段）不同时，就会出现此问题。由于长度的不同，sRNAminer 会在一步模式下将该测序文件识别为经过接头修饰的数据，这意味着 sRNAminer 不会对接头进行修剪。所以这样一来，就不能运行单步模式了，而是一步步分析（没那么难，按照说明操作就可以了，不用担心）。
> 
> 建议您先快速检查一下您的测序数据，看看是否存在上述问题。@wangyuhu123
是的，感谢您的回复，我目前正在使用这款软件一步一步分析，再次感谢您的回复！
