### ISSUE TITLE
Data_cleaning_Database无法下载

### ISSUE THREAD

**Issue by wuxiaopei0509** [kli28/sRNAminer#4]
你好，[Data_cleaning_Database.zip]包含Rfam_withoutMIR.fa么(https://github.com/kli28/sRNAminer/releases/download/v1.1.2/Data_cleaning_Database.zip)
在上面的连接里无法下载是怎么回事呢？能否提供一个可供下载的版本？
谢谢！

**Comment by kli28** [comment]
> 你好，[Data_cleaning_Database.zip]包含Rfam_withoutMIR.fa么(https://github.com/kli28/sRNAminer/releases/download/v1.1.2/Data_cleaning_Database.zip) 在上面的连接里无法下载是怎么回事呢？能否提供一个可供下载的版本？ 谢谢！

你好，我尝试过了，没有问题，请切换网络试试，谢谢。
Hi， I have tried and the download link worked well. Please check your network. Thank you.
