### ISSUE TITLE
过滤完、建立索引后 无法进行sRNA的比对和注释

### ISSUE THREAD

**Issue by wydsqgg** [kli28/sRNAminer#5]
您好，我在进行如下命令后
![image](https://github.com/user-attachments/assets/b73cd693-9228-4f5e-bfd5-1d7e84ac5a91)
sRNAminer One_step_sRNAminer -g /data1/jfhe/HJF_240918_sRNA_seq/ZmNAM/ZmB73-NAM5.0_genomic.fa -i /data1/jfhe/HJF_240918_sRNA_seq/clean_data/OE_1.fq -p 60 --nd /data1/jfhe/HJF_240918_sRNA_seq/ncRNA_filter/Rfam_ncRNA.fa --od /data1/jfhe/HJF_240918_sRNA_seq/Organelle/Organelle.fa --miRNA --PHAS21 --PHAS24 --hc_siRNA -o ./
在建立文件夹和索引后，过滤后，没有进行sRNA的比对和注释，请您帮我解答一下。
![image](https://github.com/user-attachments/assets/d9af70e7-cc5a-4f21-ba8e-55410eddc4af)
[OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log](https://github.com/user-attachments/files/17109851/OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log)
[One_Step_sRNAminer.log](https://github.com/user-attachments/files/17109855/One_Step_sRNAminer.log)

**Comment by kli28** [comment]
This problem might be caused by the blast version, and please change to 2.12

**Comment by kli28** [comment]
> 您好，我在进行如下命令后 ![image](https://private-user-images.githubusercontent.com/144693719/370173051-b73cd693-9228-4f5e-bfd5-1d7e84ac5a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjI1ODIsIm5iZiI6MTcyNzE2MjI4MiwicGF0aCI6Ii8xNDQ2OTM3MTkvMzcwMTczMDUxLWI3M2NkNjkzLTkyMjgtNGY1ZS1iZmQ1LTFkN2U4NGFjNWE5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwNzE4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTBlZGRiYmQ0MTY4ZDA3ZGIyZWJkN2ExZGM4ZjQ3YjdhYjYxMjVkYzZlY2FmZjhkMGZjZDM0NTU4M2VhOWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rxblYTNx1uNn1vHJigS1G9u_48EU8sJmop8cTgV9Oco) sRNAminer One_step_sRNAminer -g /data1/jfhe/HJF_240918_sRNA_seq/ZmNAM/ZmB73-NAM5.0_genomic.fa -i /data1/jfhe/HJF_240918_sRNA_seq/clean_data/OE_1.fq -p 60 --nd /data1/jfhe/HJF_240918_sRNA_seq/ncRNA_filter/Rfam_ncRNA.fa --od /data1/jfhe/HJF_240918_sRNA_seq/Organelle/Organelle.fa --miRNA --PHAS21 --PHAS24 --hc_siRNA -o ./ 在建立文件夹和索引后，过滤后，没有进行sRNA的比对和注释，请您帮我解答一下。 ![image](https://private-user-images.githubusercontent.com/144693719/370173738-d9af70e7-cc5a-4f21-ba8e-55410eddc4af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjI1ODIsIm5iZiI6MTcyNzE2MjI4MiwicGF0aCI6Ii8xNDQ2OTM3MTkvMzcwMTczNzM4LWQ5YWY3MGU3LWNjNWEtNGYyMS1iYThlLTU1NDEwZWRkYzRhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwNzE4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzlkZmZjZmNkMzc5YjU4MWUwZjM1MDlkNDRkMTIzNGMzM2ZhNTIzYzYwNmRhZGRhYTY2M2UwMDEyMjdmMWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XVWiaiQBO4Z0LD0f4lTv_ICEDGApRbRJThMsirdo_io) [OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log](https://github.com/user-attachments/files/17109851/OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log) [One_Step_sRNAminer.log](https://github.com/user-attachments/files/17109855/One_Step_sRNAminer.log)

This question might be caused by the blast version, you can change to 2.12.

**Comment by wydsqgg** [comment]
> This problem might be caused by the blast version, and please change to 2.12

您好，可以青柠说的具体一下吗？具体要怎么操作执行呢，是要重新指定一个blast吗，我下载了一个blast 2.12

**Comment by wydsqgg** [comment]
我按照您的建议，在conda环境下安装了blast，结果还是一样，没有进行比对。

**Comment by kli28** [comment]
> 我按照您的建议，在conda环境下安装了blast，结果还是一样，没有进行比对。

I checked your [OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log and found that you didn't put your bowtie index of your data cleaning database sequence file(Rfam*.fa and Organelle.fa) together with your database sequence files. please put them in the same directory.

**Comment by wydsqgg** [comment]
> > 我按照您的建议，在conda环境下安装了blast，结果还是一样，没有进行比对。
> 
> I checked your [OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log and found that you didn't put your bowtie index of your data cleaning database sequence file(Rfam*.fa and Organelle.fa) together with your database sequence files. please put them in the same directory.

很抱歉再次打扰您，我将所有文件放在一个文件夹下运行，还是出现了一样的问题。
![image](https://github.com/user-attachments/assets/05ea6a1f-210a-42de-b7e6-9bb47c0c4313)
![image](https://github.com/user-attachments/assets/dbbad663-4579-487e-acb8-8ab7f8c91bac)

**Comment by kli28** [comment]
> > > 我按照您的建议，在conda环境下安装了blast，结果还是一样，没有进行比对。
> > 
> > 
> > I checked your [OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log and found that you didn't put your bowtie index of your data cleaning database sequence file(Rfam*.fa and Organelle.fa) together with your database sequence files. please put them in the same directory.
> 
> 很抱歉再次打扰您，我将所有文件放在一个文件夹下运行，还是出现了一样的问题。 ![image](https://private-user-images.githubusercontent.com/144693719/370569841-05ea6a1f-210a-42de-b7e6-9bb47c0c4313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDc3OTIsIm5iZiI6MTcyNzI0NzQ5MiwicGF0aCI6Ii8xNDQ2OTM3MTkvMzcwNTY5ODQxLTA1ZWE2YTFmLTIxMGEtNDJkZS1iN2U2LTliYjQ3YzBjNDMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwNjU4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTExNDgyYmNmMDEwNGIyZWNkMzAyZDQzNDU1Y2I2MDI5OTYxYjY5YWIyMGMzNGU0MmJhYzcyOGFmMjBkY2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wgjDZ5CQNGDy3qRr-XrKpdoZT61kYHVW8bYPQ55FCR0) ![image](https://private-user-images.githubusercontent.com/144693719/370569972-dbbad663-4579-487e-acb8-8ab7f8c91bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDc3OTIsIm5iZiI6MTcyNzI0NzQ5MiwicGF0aCI6Ii8xNDQ2OTM3MTkvMzcwNTY5OTcyLWRiYmFkNjYzLTQ1NzktNDg3ZS1hY2I4LThhYjdmOGM5MWJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwNjU4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODYxMjMyMWQ2MDc4MzFiZmNlNzM3OGFmZmE5YzBhNmM4ZDBkMGVlNjIzZGU2Y2Y5OTFkMzE4YTc4NzI5ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0xdZAwCWVlTXuq_JWhbNp6cp89oNSf9cL8GSYCYrhRA)

Looks like you building the data_cleaning_database by yourself. Your error showed that the basename is error. You need to construct your index using your sequence file name, such as "Rfam_ncRNA.fa".

**Comment by wydsqgg** [comment]
> > > > 我按照您的建议，在conda环境下安装了blast，结果还是一样，没有进行比对。
> > > 
> > > 
> > > I checked your [OE_1.fq.trimmed.mc.no_rRNA.fa.rfam.log and found that you didn't put your bowtie index of your data cleaning database sequence file(Rfam*.fa and Organelle.fa) together with your database sequence files. please put them in the same directory.
> > 
> > 
> > 很抱歉再次打扰您，我将所有文件放在一个文件夹下运行，还是出现了一样的问题。 ![image](https://private-user-images.githubusercontent.com/144693719/370569841-05ea6a1f-210a-42de-b7e6-9bb47c0c4313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDc3OTIsIm5iZiI6MTcyNzI0NzQ5MiwicGF0aCI6Ii8xNDQ2OTM3MTkvMzcwNTY5ODQxLTA1ZWE2YTFmLTIxMGEtNDJkZS1iN2U2LTliYjQ3YzBjNDMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwNjU4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTExNDgyYmNmMDEwNGIyZWNkMzAyZDQzNDU1Y2I2MDI5OTYxYjY5YWIyMGMzNGU0MmJhYzcyOGFmMjBkY2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wgjDZ5CQNGDy3qRr-XrKpdoZT61kYHVW8bYPQ55FCR0) ![image](https://private-user-images.githubusercontent.com/144693719/370569972-dbbad663-4579-487e-acb8-8ab7f8c91bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDc3OTIsIm5iZiI6MTcyNzI0NzQ5MiwicGF0aCI6Ii8xNDQ2OTM3MTkvMzcwNTY5OTcyLWRiYmFkNjYzLTQ1NzktNDg3ZS1hY2I4LThhYjdmOGM5MWJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwNjU4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODYxMjMyMWQ2MDc4MzFiZmNlNzM3OGFmZmE5YzBhNmM4ZDBkMGVlNjIzZGU2Y2Y5OTFkMzE4YTc4NzI5ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0xdZAwCWVlTXuq_JWhbNp6cp89oNSf9cL8GSYCYrhRA)
> 
> Looks like you building the data_cleaning_database by yourself. Your error showed that the basename is error. You need to construct your index using your sequence file name, such as "Rfam_ncRNA.fa".

OK，这个问题已经解决，已经可以成功运行并输出结果，十分感谢作者，非常有耐心的解答，sRNAMiner 是一款十分好用的sRNA分析工具。
